services:
   reverse-proxy:
      image: ghcr.io/ola-awaly/mastermind/reverse-proxy:latest
      networks:
         - mastermind
         - cvgenerator
      ports:
         - 80:80
         - 81:81
         - 3000:3000
      restart: unless-stopped
networks:
   mastermind:
      driver: bridge
   cvgenerator:
      driver: bridge
