name: CI/CD reverse proxy workflow
on:
   push:
      branches:
         - main
env:
   SERVER_IP: 15.235.198.17
   SERVER_USER: ubuntu

jobs:
   build:
      runs-on: ubuntu-latest
      permissions:
         packages: write

      steps:
         - name: checkout code
           uses: actions/checkout@v4

         - name: mis en place de buildx
           uses: docker/setup-buildx-action@v3

         - name: login sur github packages Registry
           uses: docker/login-action@v3
           with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{ secrets.GITHUB_TOKEN }}

         - name: récupérationdes metadonnées
           id: metadata
           uses: docker/metadata-action@v5
           with:
              images: ghcr.io/${{ github.repository }}/reverse-proxy

         - name: build et push
           uses: docker/build-push-action@v5
           with:
              push: true
              tags: ghcr.io/${{ github.repository }}/reverse-proxy
              context: ./
              file: Dockerfile.prod
              cache-from: type=gha
              cache-to: type=gha,mode=max
              no-cache: true # Correction ici
   deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
         - name: checkout le code
           uses: actions/checkout@v4

         - name: déployer sur le vps
           run: |
              eval $(ssh-agent -s)
              ssh-add - <<< "${{ secrets.OVH_PROD_PKEY}}"
              mkdir -p  ~/.ssh
              ssh-keyscan -H ${{ env.SERVER_IP }} >> ~/.ssh/known_hosts
              scp compose.prod.yml ${{ env.SERVER_USER }}@${{ env.SERVER_IP }}:/home/${{ env.SERVER_USER }}/proxy/compose.prod.yml
              ssh ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} "

              docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} &&
               docker compose -f /home/${{ env.SERVER_USER }}/proxy/compose.prod.yml pull &&
              docker compose -f /home/${{ env.SERVER_USER }}/proxy/compose.prod.yml up -d --force-recreate"
